### ISSUE TITLE
Showing info from the currently not discharging battery

### ISSUE THREAD

**Issue by hujberhunor** [svartalf/rust-battop#18]
I have 2 battery and battop shows info from that one that is not discharging. Linux, manjaro.
![2022-05-04_13-47](https://user-images.githubusercontent.com/50179148/166675221-f26a4eb4-3893-4d79-946c-07249cd5c363.png)

**Comment by MrRinkana** [comment]
From the "Usage" section of the readme:

> ...
> Left and right arrows can be used to switch between different system batteries (if available).
> ...

You can see the other battery at the top of the image in the "batteries section" so you should be able to switch to the battery you are interested in.

**Comment by MrRinkana** [comment]
Maybe this can be closed @hujberhunor ?
