### ISSUE TITLE
Build failing on Fedora 36

### ISSUE THREAD

**Issue by j-px** [svartalf/rust-battop#20]
Hi, just tried building this on Fedora Linux 36 (Workstation Edition). It failed at building uom, and it seems to be [this exact issue](https://github.com/iliekturtles/uom/issues/224).

Without much experience in rust / cargo / the build system, I tried looking at Cargo.toml if there's a direct dependency on an older uom version, but there's none, right?

I'm not sure what to do, and just reporting what I experienced.

**Comment by frosth555** [comment]
it's fix from aur, just run it from sources directory. 
`sed -i 's/battery = "^0.7"/battery = "^0.7.5"/' Cargo.toml`

**Comment by j-px** [comment]
That worked, thanks!
